"""Hand-verified exercise -> muscle-group map (highest-priority layer).

Keyed by the exact Hevy `exercise_title` string. Built from a real
3,474-row export (89 exercises), not guessed. Attribution rule (CLAUDE.md
§5): hard-set counts credit `primary_muscle` only — secondary muscles are
not fractionally counted, since that's a contested modeling choice, not a
fact. Anything absent here falls through to the broader external dataset
and fuzzy matching in `resolver.get_exercise_info`.
"""

from app.domain.muscle_map.models import ExerciseInfo

EXERCISE_MUSCLE_MAP: dict[str, ExerciseInfo] = {
    "90 one arm lock off (assisted)": ExerciseInfo(
        display_name="90 One Arm Lock Off (Assisted)",
        primary_muscle="back",
        secondary_muscles=("biceps", "forearms"),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "Archer pullups": ExerciseInfo(
        display_name="Archer Pull-Up",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "Back Extension (Weighted Hyperextension)": ExerciseInfo(
        display_name="Back Extension (Weighted Hyperextension)",
        primary_muscle="back",
        secondary_muscles=("glutes", "hamstrings"),
        movement_pattern="hinge",
        is_streetlift_lift=False,
    ),
    "Behind the Back Bicep Wrist Curl (Barbell)": ExerciseInfo(
        display_name="Behind the Back Bicep Wrist Curl (Barbell)",
        primary_muscle="forearms",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Behind the Back Curl (Cable)": ExerciseInfo(
        display_name="Behind the Back Curl (Cable)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Bench Press (Barbell)": ExerciseInfo(
        display_name="Bench Press (Barbell)",
        primary_muscle="chest",
        secondary_muscles=("triceps", "shoulders"),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Bench Press (Dumbbell)": ExerciseInfo(
        display_name="Bench Press (Dumbbell)",
        primary_muscle="chest",
        secondary_muscles=("triceps", "shoulders"),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Bench Press (Smith Machine)": ExerciseInfo(
        display_name="Bench Press (Smith Machine)",
        primary_muscle="chest",
        secondary_muscles=("triceps", "shoulders"),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Bent Over Row (Barbell)": ExerciseInfo(
        display_name="Bent Over Row (Barbell)",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Bent Over Row (Smith)": ExerciseInfo(
        display_name="Bent Over Row (Smith Machine)",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Bicep Curl (Barbell)": ExerciseInfo(
        display_name="Bicep Curl (Barbell)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Bicep Curl (Cable)": ExerciseInfo(
        display_name="Bicep Curl (Cable)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Bicep Curl (Dumbbell)": ExerciseInfo(
        display_name="Bicep Curl (Dumbbell)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Bicep Curl (Machine)": ExerciseInfo(
        display_name="Bicep Curl (Machine)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Bulgarian Split Squat": ExerciseInfo(
        display_name="Bulgarian Split Squat",
        primary_muscle="quads",
        secondary_muscles=("glutes", "hamstrings"),
        movement_pattern="squat",
        is_streetlift_lift=False,
    ),
    "Butterfly (Pec Deck)": ExerciseInfo(
        display_name="Butterfly (Pec Deck)",
        primary_muscle="chest",
        secondary_muscles=("shoulders",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Calf Extension (Machine)": ExerciseInfo(
        display_name="Calf Extension (Machine)",
        primary_muscle="calves",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Calf Press (Machine)": ExerciseInfo(
        display_name="Calf Press (Machine)",
        primary_muscle="calves",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Chest Dip": ExerciseInfo(
        display_name="Chest Dip",
        primary_muscle="chest",
        secondary_muscles=("triceps", "shoulders"),
        movement_pattern="push",
        is_streetlift_lift=True,
    ),
    "Chest Dip (Weighted)": ExerciseInfo(
        display_name="Chest Dip (Weighted)",
        primary_muscle="chest",
        secondary_muscles=("triceps", "shoulders"),
        movement_pattern="push",
        is_streetlift_lift=True,
    ),
    "Chest Fly (Dumbbell)": ExerciseInfo(
        display_name="Chest Fly (Dumbbell)",
        primary_muscle="chest",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Chest Fly (Machine)": ExerciseInfo(
        display_name="Chest Fly (Machine)",
        primary_muscle="chest",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Chest Press (Machine)": ExerciseInfo(
        display_name="Chest Press (Machine)",
        primary_muscle="chest",
        secondary_muscles=("triceps", "shoulders"),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Chest Supported Incline Row (Dumbbell)": ExerciseInfo(
        display_name="Chest Supported Incline Row (Dumbbell)",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Cross Body Hammer Curl": ExerciseInfo(
        display_name="Cross Body Hammer Curl",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Crunch (Machine)": ExerciseInfo(
        display_name="Crunch (Machine)",
        primary_muscle="core",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Dumbbell Row": ExerciseInfo(
        display_name="Dumbbell Row",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Explosive pull ups": ExerciseInfo(
        display_name="Explosive Pull-Up",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "Face Pull": ExerciseInfo(
        display_name="Face Pull",
        primary_muscle="shoulders",
        secondary_muscles=("back",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Hammer Curl (Cable)": ExerciseInfo(
        display_name="Hammer Curl (Cable)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Hammer Curl (Dumbbell)": ExerciseInfo(
        display_name="Hammer Curl (Dumbbell)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Hanging Leg Raise": ExerciseInfo(
        display_name="Hanging Leg Raise",
        primary_muscle="core",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Hip Thrust (Machine)": ExerciseInfo(
        display_name="Hip Thrust (Machine)",
        primary_muscle="glutes",
        secondary_muscles=("hamstrings",),
        movement_pattern="hinge",
        is_streetlift_lift=False,
    ),
    "Incline Bench Press (Barbell)": ExerciseInfo(
        display_name="Incline Bench Press (Barbell)",
        primary_muscle="chest",
        secondary_muscles=("shoulders", "triceps"),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Incline Bench Press (Dumbbell)": ExerciseInfo(
        display_name="Incline Bench Press (Dumbbell)",
        primary_muscle="chest",
        secondary_muscles=("shoulders", "triceps"),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Incline Bench Press (Smith Machine)": ExerciseInfo(
        display_name="Incline Bench Press (Smith Machine)",
        primary_muscle="chest",
        secondary_muscles=("shoulders", "triceps"),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Kelso Shrugs": ExerciseInfo(
        display_name="Kelso Shrugs",
        primary_muscle="back",
        secondary_muscles=(),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Lat Pulldown (Cable)": ExerciseInfo(
        display_name="Lat Pulldown (Cable)",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Lateral Raise (Cable)": ExerciseInfo(
        display_name="Lateral Raise (Cable)",
        primary_muscle="shoulders",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Lateral Raise (Dumbbell)": ExerciseInfo(
        display_name="Lateral Raise (Dumbbell)",
        primary_muscle="shoulders",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Leg Extension (Machine)": ExerciseInfo(
        display_name="Leg Extension (Machine)",
        primary_muscle="quads",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Leg Press (Machine)": ExerciseInfo(
        display_name="Leg Press (Machine)",
        primary_muscle="quads",
        secondary_muscles=("glutes",),
        movement_pattern="squat",
        is_streetlift_lift=False,
    ),
    "Low Cable Fly Crossovers": ExerciseInfo(
        display_name="Low Cable Fly Crossovers",
        primary_muscle="chest",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Muscle Up": ExerciseInfo(
        display_name="Muscle-Up",
        primary_muscle="back",
        secondary_muscles=("chest", "triceps", "biceps"),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "One arm pull up (assisted)": ExerciseInfo(
        display_name="One Arm Pull-Up (Assisted)",
        primary_muscle="back",
        secondary_muscles=("biceps", "forearms"),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "Overhead Press (Barbell)": ExerciseInfo(
        display_name="Overhead Press (Barbell)",
        primary_muscle="shoulders",
        secondary_muscles=("triceps",),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Overhead Press (Smith Machine)": ExerciseInfo(
        display_name="Overhead Press (Smith Machine)",
        primary_muscle="shoulders",
        secondary_muscles=("triceps",),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Overhead Triceps Extension (Cable)": ExerciseInfo(
        display_name="Overhead Triceps Extension (Cable)",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Preacher Curl (Dumbbell)": ExerciseInfo(
        display_name="Preacher Curl (Dumbbell)",
        primary_muscle="biceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Preacher Curl (Machine)": ExerciseInfo(
        display_name="Preacher Curl (Machine)",
        primary_muscle="biceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Pull Up": ExerciseInfo(
        display_name="Pull-Up",
        primary_muscle="back",
        secondary_muscles=("biceps", "forearms"),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "Pull Up (Assisted)": ExerciseInfo(
        display_name="Pull-Up (Assisted)",
        primary_muscle="back",
        secondary_muscles=("biceps", "forearms"),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "Pull Up (Weighted)": ExerciseInfo(
        display_name="Pull-Up (Weighted)",
        primary_muscle="back",
        secondary_muscles=("biceps", "forearms"),
        movement_pattern="pull",
        is_streetlift_lift=True,
    ),
    "Rear Delt Reverse Fly (Cable)": ExerciseInfo(
        display_name="Rear Delt Reverse Fly (Cable)",
        primary_muscle="shoulders",
        secondary_muscles=("back",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Rear Delt Reverse Fly (Dumbbell)": ExerciseInfo(
        display_name="Rear Delt Reverse Fly (Dumbbell)",
        primary_muscle="shoulders",
        secondary_muscles=("back",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Rear Delt Reverse Fly (Machine)": ExerciseInfo(
        display_name="Rear Delt Reverse Fly (Machine)",
        primary_muscle="shoulders",
        secondary_muscles=("back",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Reverse Curl (Barbell)": ExerciseInfo(
        display_name="Reverse Curl (Barbell)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Reverse Curl (Cable)": ExerciseInfo(
        display_name="Reverse Curl (Cable)",
        primary_muscle="biceps",
        secondary_muscles=("forearms",),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Romanian Deadlift (Barbell)": ExerciseInfo(
        display_name="Romanian Deadlift (Barbell)",
        primary_muscle="hamstrings",
        secondary_muscles=("glutes", "back"),
        movement_pattern="hinge",
        is_streetlift_lift=False,
    ),
    "Running": ExerciseInfo(
        display_name="Running",
        primary_muscle="cardio",
        secondary_muscles=(),
        movement_pattern="cardio",
        is_streetlift_lift=False,
    ),
    "Seated Cable Row - Bar Grip": ExerciseInfo(
        display_name="Seated Cable Row (Bar Grip)",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Seated Cable Row - V Grip (Cable)": ExerciseInfo(
        display_name="Seated Cable Row (V Grip)",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Seated Incline Curl (Dumbbell)": ExerciseInfo(
        display_name="Seated Incline Curl (Dumbbell)",
        primary_muscle="biceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Seated Leg Curl (Machine)": ExerciseInfo(
        display_name="Seated Leg Curl (Machine)",
        primary_muscle="hamstrings",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Seated Palms Up Wrist Curl": ExerciseInfo(
        display_name="Seated Palms Up Wrist Curl",
        primary_muscle="forearms",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Seated Row (Machine)": ExerciseInfo(
        display_name="Seated Row (Machine)",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Seated Shoulder Press (Machine)": ExerciseInfo(
        display_name="Seated Shoulder Press (Machine)",
        primary_muscle="shoulders",
        secondary_muscles=("triceps",),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Shoulder Press (Dumbbell)": ExerciseInfo(
        display_name="Shoulder Press (Dumbbell)",
        primary_muscle="shoulders",
        secondary_muscles=("triceps",),
        movement_pattern="push",
        is_streetlift_lift=False,
    ),
    "Single Arm Lateral Raise (Cable)": ExerciseInfo(
        display_name="Single Arm Lateral Raise (Cable)",
        primary_muscle="shoulders",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Single Arm Triceps Pushdown (Cable)": ExerciseInfo(
        display_name="Single Arm Triceps Pushdown (Cable)",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Single Leg Standing Calf Raise (Dumbbell)": ExerciseInfo(
        display_name="Single Leg Standing Calf Raise (Dumbbell)",
        primary_muscle="calves",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Single Leg Standing Calf Raise (Machine)": ExerciseInfo(
        display_name="Single Leg Standing Calf Raise (Machine)",
        primary_muscle="calves",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Skullcrusher (Barbell)": ExerciseInfo(
        display_name="Skullcrusher (Barbell)",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Skullcrusher (Dumbbell)": ExerciseInfo(
        display_name="Skullcrusher (Dumbbell)",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Squat (Barbell)": ExerciseInfo(
        display_name="Squat (Barbell)",
        primary_muscle="quads",
        secondary_muscles=("glutes", "hamstrings"),
        movement_pattern="squat",
        is_streetlift_lift=True,
    ),
    "Squat (Machine)": ExerciseInfo(
        display_name="Squat (Machine)",
        primary_muscle="quads",
        secondary_muscles=("glutes", "hamstrings"),
        movement_pattern="squat",
        is_streetlift_lift=True,
    ),
    "Squat (Smith Machine)": ExerciseInfo(
        display_name="Squat (Smith Machine)",
        primary_muscle="quads",
        secondary_muscles=("glutes", "hamstrings"),
        movement_pattern="squat",
        is_streetlift_lift=True,
    ),
    "Standing Calf Raise (Barbell)": ExerciseInfo(
        display_name="Standing Calf Raise (Barbell)",
        primary_muscle="calves",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Standing Calf Raise (Machine)": ExerciseInfo(
        display_name="Standing Calf Raise (Machine)",
        primary_muscle="calves",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "T Bar Row": ExerciseInfo(
        display_name="T-Bar Row",
        primary_muscle="back",
        secondary_muscles=("biceps",),
        movement_pattern="pull",
        is_streetlift_lift=False,
    ),
    "Treadmill": ExerciseInfo(
        display_name="Treadmill",
        primary_muscle="cardio",
        secondary_muscles=(),
        movement_pattern="cardio",
        is_streetlift_lift=False,
    ),
    "Tricep Pushdown (Hall Gym)": ExerciseInfo(
        display_name="Tricep Pushdown",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Tricep Resistance Band": ExerciseInfo(
        display_name="Tricep Resistance Band",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Triceps Dip": ExerciseInfo(
        display_name="Triceps Dip",
        primary_muscle="triceps",
        secondary_muscles=("chest", "shoulders"),
        movement_pattern="push",
        is_streetlift_lift=True,
    ),
    "Triceps Extension (Cable)": ExerciseInfo(
        display_name="Triceps Extension (Cable)",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Triceps Kickback (Cable)": ExerciseInfo(
        display_name="Triceps Kickback (Cable)",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Triceps Kickback (Dumbbell)": ExerciseInfo(
        display_name="Triceps Kickback (Dumbbell)",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Triceps Pushdown": ExerciseInfo(
        display_name="Triceps Pushdown",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
    "Triceps Rope Pushdown": ExerciseInfo(
        display_name="Triceps Rope Pushdown",
        primary_muscle="triceps",
        secondary_muscles=(),
        movement_pattern="isolation",
        is_streetlift_lift=False,
    ),
}
