"""create workouts and workout_sets

Revision ID: 614f1a999a92
Revises:
Create Date: 2026-07-13 11:45:27.416165

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "614f1a999a92"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector once, at the base migration — a project-wide prerequisite
    # for the RAG corpus (Phase 3). Idempotent; the pgvector/pgvector image
    # ships the extension, so this only registers it in this database.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workouts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("raw_storage_key", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "content_hash", name="uq_workouts_user_content_hash"),
        sa.UniqueConstraint("user_id", "external_id", name="uq_workouts_user_external_id"),
    )
    op.create_index(
        "ix_workouts_user_started_at", "workouts", ["user_id", "started_at"], unique=False
    )
    op.create_table(
        "workout_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_name", sa.String(), nullable=False),
        sa.Column("exercise_slug", sa.String(), nullable=False),
        sa.Column("set_index", sa.Integer(), nullable=False),
        sa.Column("set_type", sa.String(), nullable=False),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("duration_s", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("superset_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_workout_sets_exercise_slug"), "workout_sets", ["exercise_slug"], unique=False
    )
    op.create_index(
        op.f("ix_workout_sets_workout_id"), "workout_sets", ["workout_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workout_sets_workout_id"), table_name="workout_sets")
    op.drop_index(op.f("ix_workout_sets_exercise_slug"), table_name="workout_sets")
    op.drop_table("workout_sets")
    op.drop_index("ix_workouts_user_started_at", table_name="workouts")
    op.drop_table("workouts")
    # ### end Alembic commands ###
