"""create science_corpus

Revision ID: 72aaaadaad77
Revises: 614f1a999a92
Create Date: 2026-07-13 17:28:54.848024

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72aaaadaad77"
down_revision: str | Sequence[str] | None = "614f1a999a92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "science_corpus",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pubmed_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("finding_text", sa.String(), nullable=False),
        sa.Column("abstract_text", sa.String(), nullable=False),
        sa.Column("topic_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("citation", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("condensation_reviewed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("science_corpus")
    # ### end Alembic commands ###
